name: meal_monkey
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_do: ^2.1.0
  flutter_screenutil: ^5.4.0+1
  flutter_gen: ^4.1.6
  easy_localization: ^3.0.0
  pin_code_fields: ^7.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/bottom_nav/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/products/
    - assets/langs/
  fonts:
    - family: Etihad
      fonts:
        - asset: assets/fonts/etihad_altis/etihad.otf
    - family: MetroBlack
      fonts:
        - asset: assets/fonts/metropolis/black.otf
    - family: MetroBlackItalic
      fonts:
        - asset: assets/fonts/metropolis/black_italic.otf
    - family: MetroBold
      fonts:
        - asset: assets/fonts/metropolis/bold.otf
    - family: MetroBoldItalic
      fonts:
        - asset: assets/fonts/metropolis/extra_bold_italic.otf
    - family: MetroRegular
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf